# -*- coding: utf-8 -*-
"""lab4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_tF-8Vzafdst8i5Gc0oHxszN36LIjFEL

**Part 0: Repository and API-key setup**
"""

# API-key setup — DO NOT hard-code your key in this cell.
import os

# --- Google Colab (Secrets panel) ---
# We are using Colab, so we import userdata to safely grab our secret key!
from google.colab import userdata

# TODO: set API_KEY using ONE of the methods above.
# Make sure you have created a secret called "GROQ_API_KEY" in the left-hand key menu
API_KEY = userdata.get("GROQ_API_KEY")

# OpenAI-compatible client (works for Groq and OpenAI; Gemini users see their docs):
from openai import OpenAI

client = OpenAI(
    api_key=API_KEY,
    base_url="https://api.groq.com/openai/v1",   # remove this line if using OpenAI itself
)
MODEL = "llama-3.3-70b-versatile"                # or your provider's model name

print("Client ready.")

"""**Section 1 — Talking to an LLM Programmatically**"""

# TODO: Write a helper function you will reuse for the WHOLE lab:
def ask_llm(user_prompt, system_prompt="You are a helpful assistant.", temperature=0.7, max_tokens=500):
    # This sends our message to the AI
    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user",   "content": user_prompt},
        ],
        temperature=temperature,
        max_tokens=max_tokens,
    )

    # We print this so we can see how much "brain power" the AI used
    print(f"[Tokens used: {response.usage.total_tokens}]")

    # This returns just the text answer so it is easy to read
    return response.choices[0].message.content

# TODO: Call it once with a simple question and print the answer.
# TODO: Print response.usage as well — how many tokens did your call consume?
simple_question = "What is the capital city of Ghana?"
answer = ask_llm(simple_question)
print("\nAnswer from AI:")
print(answer)

"""**Student Reasoning — Anatomy of a call**
*1. What is the difference between the `system` and `user` roles? Give an example of something that belongs in each.*
*2. What is a token, roughly? Why do API providers bill per token rather than per request?*

> **Answer:**
> 1. The `system` role is like setting the rules of a game; it tells the AI how to act (Example: "You are a grumpy math teacher"). The `user` role is what we actually ask it (Example: "What is 2 plus 2?").
> 2. A token is basically a piece of a word (like a syllable). Providers bill by token because generating each piece of a word requires computer power. A long answer costs them more energy than a short one!

**Part 1.2 — Temperature: the randomness dial**
"""

# TODO: Ask the SAME question 5 times at temperature=0.0 and 5 times at temperature=1.2.
#   A good test question: "Suggest a name for a savings product for market traders in Accra."

# TODO: Print all 10 answers, grouped by temperature.

question = "Suggest a name for a savings product for market traders in Accra."

# These lists will store the answers.
answers_0 = []
answers_12 = []

# Ask the question 5 times with temperature 0.0.
for i in range(5):
    answer = ask_llm(
        question,
        temperature=0.0,
        max_tokens=50
    )

    answers_0.append(answer)

# Ask the question 5 times with temperature 1.2.
for i in range(5):
    answer = ask_llm(
        question,
        temperature=1.2,
        max_tokens=50
    )

    answers_12.append(answer)


# Print the low-temperature answers.
print("Temperature = 0.0")

for i, answer in enumerate(answers_0, start=1):
    print(f"{i}. {answer}")


# Print the high-temperature answers.
print("\nTemperature = 1.2")

for i, answer in enumerate(answers_12, start=1):
    print(f"{i}. {answer}")

"""**Student Reasoning — Temperature**
*What did you observe at each temperature? For the loan decision-support system you are about to build, which temperature regime is appropriate, and why?*

> **Answer:**
> At temperature 0.0, the answers were usually very similar because the model was less random. At temperature 1.2, the answers were more varied and creative. For loan extraction and decision support, I would use a low temperature, such as 0.0, because we want stable and factual results. A higher temperature is better for creative ideas, not for important facts.

**Section 2 — The Dataset: Loan Application Letters**
"""

LETTERS = {
"L001": """Dear Sir/Madam,
My name is Akosua Mensah and I have been selling provisions at Makola Market for 12 years.
I am applying for a loan of GHS 8,000 to buy a deep freezer and expand into frozen foods.
My current stall makes about GHS 900 profit each month. I have saved GHS 2,500 with your
susu scheme over the past two years and I have never missed a contribution. I can repay
GHS 450 monthly over 20 months. My sister, a teacher, will stand as my guarantor.
Thank you for considering my application.""",

"L002": """Hello,
I am Kwame Boateng, a commercial driver in Kumasi. I need GHS 25,000 urgently to repair my
trotro engine and settle some personal debts. Business has been slow but it will surely
pick up after the festive season. I can pay back whenever the money comes. I do not have
collateral at the moment but God willing everything will be fine. Please help me quickly.""",

"L003": """Dear Loan Committee,
I am Efua Darko, owner of Darko Fashions, a registered dressmaking business in Takoradi
(registration no. BN-2019-4482). I employ three apprentices. I request GHS 15,000 to
purchase two industrial sewing machines and fabric stock ahead of the Christmas season.
Last year my December revenue alone was GHS 22,000; monthly profit averages GHS 2,800.
I hold a fixed deposit of GHS 5,000 with GCB which I can pledge. Proposed repayment:
GHS 1,100 monthly for 15 months. Attached are my sales records for the past 18 months.""",

"L004": """Good day,
My name is Yaw Owusu. I want a loan for my poultry farm at Nsawam. The amount is GHS 12,000
for feed and 500 new layers. I started the farm last year. Sometimes I make good money,
around GHS 1,500 in a good month, but bird flu affected us in March and I lost many birds.
I am rebuilding now. I can repay in 18 months. My uncle has agreed to guarantee the loan
with his taxi.""",

"L005": """Dear Manager,
I am writing on behalf of the Adenta Women's Weaving Cooperative (14 members). We seek
GHS 30,000 to buy a bulk order of yarn directly from the factory, cutting out middlemen and
raising our margins from 15% to about 35%. The cooperative has operated for 6 years and
holds GHS 9,000 in our group account. We propose repayment of GHS 2,000 monthly over
16 months, backed by our group savings and joint liability agreement.""",

"L006": """Hi,
This is Kofi. I saw your advert. I want GHS 50,000 to start a car washing business, a
provision shop, and also import phones from Dubai. I am 22 and full of energy. I have not
started any of these yet but my friends say I am very business minded. I will pay back in
one year when the businesses are booming. No collateral but I am trustworthy.""",
}

# Gold-standard labels for three letters (for Section 4 evaluation):
GOLD = {
  "L001": {"applicant_name": "Akosua Mensah", "amount_ghs": 8000,  "purpose": "buy deep freezer / expand into frozen foods",
           "monthly_profit_ghs": 900,  "has_collateral_or_guarantor": True,  "repayment_months": 20},
  "L003": {"applicant_name": "Efua Darko",    "amount_ghs": 15000, "purpose": "industrial sewing machines and fabric stock",
           "monthly_profit_ghs": 2800, "has_collateral_or_guarantor": True,  "repayment_months": 15},
  "L006": {"applicant_name": "Kofi",          "amount_ghs": 50000, "purpose": "car wash, provision shop, phone imports",
           "monthly_profit_ghs": None, "has_collateral_or_guarantor": False, "repayment_months": 12},
}

print(f"{len(LETTERS)} letters loaded.")

"""**Section 3 — Prompt Engineering for the Decision Support System**

**Part 3.1 — Component 1: Summarization**
"""

# TODO: Write SUMMARY_PROMPT_V1 — your first, naive attempt (e.g. just "Summarize this:").
#   Run it on L002 and L006. Read the output critically.

# TODO: Now write SUMMARY_PROMPT_V2 as a proper template with:
#   - a system prompt giving the LLM a ROLE (e.g. "You are an assistant to a microfinance
#     loan officer...") and constraints (factual, neutral, no invented details, 3-4 sentences)
#   - a user prompt template like: f"Summarize this loan application:\n\n{letter_text}"
#   Run V2 on the same two letters at temperature=0.

# TODO: Compare V1 vs V2 outputs side by side. Keep both prompt versions in this notebook.


# Version 1: simple prompt.
SUMMARY_PROMPT_V1 = "Summarize this:\n\n{letter_text}"


# Run V1 on L002.
v1_l002 = ask_llm(
    SUMMARY_PROMPT_V1.format(letter_text=LETTERS["L002"]),
    temperature=0.7,
    max_tokens=180
)


# Run V1 on L006.
v1_l006 = ask_llm(
    SUMMARY_PROMPT_V1.format(letter_text=LETTERS["L006"]),
    temperature=0.7,
    max_tokens=180
)


# Version 2: more detailed instructions.
SUMMARY_SYSTEM_V2 = """You are an assistant to a microfinance loan officer.
Summarize loan applications in a factual and neutral way.
Use only information stated in the letter.
Do not invent, assume, or add missing facts.
Write 3-4 sentences.
Do not approve or reject the loan."""


SUMMARY_PROMPT_V2 = """Summarize this loan application:

{letter_text}"""


# Run V2 on L002 with temperature 0.
v2_l002 = ask_llm(
    SUMMARY_PROMPT_V2.format(letter_text=LETTERS["L002"]),
    system_prompt=SUMMARY_SYSTEM_V2,
    temperature=0.0,
    max_tokens=180
)


# Run V2 on L006 with temperature 0.
v2_l006 = ask_llm(
    SUMMARY_PROMPT_V2.format(letter_text=LETTERS["L006"]),
    system_prompt=SUMMARY_SYSTEM_V2,
    temperature=0.0,
    max_tokens=180
)


# Compare the two versions.
print("=" * 70)
print("L002 - V1")
print(v1_l002)

print("\nL002 - V2")
print(v2_l002)


print("\n" + "=" * 70)
print("L006 - V1")
print(v1_l006)

print("\nL006 - V2")
print(v2_l006)

"""**Student Reasoning — Summarization prompts**
**1. What concrete problems did V1's output have that V2 fixed? Quote examples.**

- V1 sometimes added details that were not clearly stated in the original letters. For example, for L006, V1 said Kofi “has no prior experience,” but the original letter only says that he “has not started any of these yet.” V2 fixed this by saying “Kofi has not yet started any of these businesses,” which stays closer to the original information. V1 also said that Kofi “offers no collateral, relying on his personal trustworthiness,” while V2 used the more neutral wording “He does not have collateral to offer, but asserts that he is trustworthy.” Overall, V2 was more factual and neutral.

2. **Why is "no invented details" an essential instruction in this application? What is this failure mode called in the LLM literature?**

- “No invented details” is important because this system is helping with loan applications. If the LLM makes up information, a loan officer could make a wrong decision about a person. For example, saying that Kofi has “no prior experience” could make his application look worse even though the original letter did not say that. When an LLM creates information that is not supported by the given text, this failure is called a hallucination.

**Part 3.2 — Component 2: Structured extraction (JSON)**
"""

import json
import pandas as pd

# TODO: Write EXTRACT_PROMPT — a template that instructs the model to return ONLY a JSON object
#   Techniques to use: explicit schema, ONE worked example (few-shot), "If a field is not stated in the letter, use null. Do not guess."
EXTRACT_SYSTEM_PROMPT = """You are a highly precise data extractor. Return ONLY a JSON object with EXACTLY these keys:
- "applicant_name" (string)
- "amount_ghs" (number)
- "purpose" (string)
- "monthly_profit_ghs" (number or null)
- "has_collateral_or_guarantor" (boolean)
- "repayment_months" (number or null)

If a field is not stated in the letter, use null. Do not guess. Do not include any text outside the JSON.

Example:
Letter: "I am Jane Doe. I want 100 GHS for a new oven."
JSON Output:
{"applicant_name": "Jane Doe", "amount_ghs": 100, "purpose": "new oven", "monthly_profit_ghs": null, "has_collateral_or_guarantor": false, "repayment_months": null}
"""

# TODO: Write extract_fields(letter_text) that calls the LLM, strips any ```json fences, json.loads() the result, and returns a dict.
def extract_fields(letter_text):
    user_prompt = f"Extract data from this letter:\n\n{letter_text}"
    # Temperature 0 keeps it strict so the JSON doesn't break
    raw_response = ask_llm(user_prompt, system_prompt=EXTRACT_SYSTEM_PROMPT, temperature=0.0)

    # Clean up formatting if the AI accidentally adds markdown fences
    clean_text = raw_response.replace("```json", "").replace("```", "").strip()

    try:
        # Convert string to a real Python dictionary
        return json.loads(clean_text)
    except Exception as e:
        print(f"Warning: Could not parse JSON. Error: {e}")
        return None

# TODO: Run it on ALL SIX letters; collect results into a pandas DataFrame and display it.
extracted_data_list = []

for letter_id, text in LETTERS.items():
    data = extract_fields(text)
    if data:
        data['Letter_ID'] = letter_id # Add the ID to keep track
        extracted_data_list.append(data)

df = pd.DataFrame(extracted_data_list)
# Let's put Letter_ID first for a nicer table view
columns = ['Letter_ID'] + [col for col in df.columns if col != 'Letter_ID']
df = df[columns]

display(df)

"""**Student Reasoning — Structured extraction**
*1. Why must the few-shot example NOT come from the six letters you are processing?*
*2. Why "use null, do not guess" — what did the model do without that instruction?*
*3. Why is temperature=0 the right choice for extraction but arguably not for creative tasks?*

> **Answer:**
> 1. If we used one of our real letters as an example, the AI might accidentally memorize the answers or just copy them for the other letters.
> 2. Without "use null", the AI wants to be helpful, so it will just invent numbers to fill in the blanks!
> 3. Temperature 0 makes the AI completely strict and predictable, which is perfect for code formatting like JSON. If we want it to write a poem (creative), we want it to surprise us with different words, which requires higher temperature.

**Part 3.3 — Component 3: The decision-support brief**
"""

# TODO: Write BRIEF_PROMPT — it receives the letter AND your extracted JSON, and must output:
#     1. Strengths (bullet points, grounded in the letter)
#     2. Risks / red flags (bullet points)
#     3. Missing information the officer should request
#     4. Suggested next step (e.g. "invite for interview") — NOT "approve" or "reject".

BRIEF_SYSTEM_PROMPT = """You are a decision-support assistant for a loan officer.
Based on the applicant's letter and the extracted data, produce a brief with EXACTLY these 4 sections:
1. Strengths (bullet points)
2. Risks / red flags (bullet points)
3. Missing information to request
4. Suggested next step

Rules:
- The final decision is made by humans. Do NOT output "approve" or "reject".
- Base everything on the provided text.
"""

# TODO: Generate briefs for ALL SIX letters. Print the briefs for L001, L002, and L006.
for letter_id in ["L001", "L002", "L006"]:
    letter_text = LETTERS[letter_id]

    # Grab the JSON string from our dataframe to feed to the prompt
    extracted_json = df[df['Letter_ID'] == letter_id].to_json(orient='records')

    user_prompt = f"Letter Text:\n{letter_text}\n\nExtracted Data:\n{extracted_json}"

    print(f"========== BRIEF FOR {letter_id} ==========")
    brief = ask_llm(user_prompt, system_prompt=BRIEF_SYSTEM_PROMPT, temperature=0.2)
    print(brief)
    print("\n")

"""**Student Reasoning — Decision support**
*1. Compare the briefs for L003 (strong application) and L006 (weak application). Did the system identify the right strengths and red flags in each?*
*2. Why did we forbid the model from outputting "approve"/"reject"? Give one practical and one ethical reason.*

> **Answer:**
> **1.** Yes, the system correctly identified the key details in both cases. For **L006** (a weak application), it flagged major risks such as zero past business experience, lack of collateral, and a vague repayment plan based purely on hope. For **L003** (a strong application), it accurately highlighted solid financial health, existing sales records, a registered business structure, and pledged collateral.
>
> **2.**
> * **Practical Reason:** AI models can hallucinate details or misinterpret text. If an AI automatically makes loan decisions, a single misread fact could cause the bank to suffer massive financial losses on bad loans or lose out on reliable borrowers.
> * **Ethical Reason:** Automating rejections removes human empathy and context. A loan officer can look beyond a poorly written letter to see a hard-working applicant, whereas an automated AI decision denies people a fair human evaluation and an opportunity to explain their business face-to-face.

### Part 3.4 — Commit your prompt templates


> **Commit hash:** 5fa2322

**Section 4 — Evaluation: Quality, Reliability, Appropriateness**

**Part 4.1 — Extraction accuracy against gold labels**
"""

# TODO: For the three letters in GOLD, compare your extracted DataFrame to the gold values field by field.
results_table = []
fields_to_check = ["applicant_name", "amount_ghs", "purpose", "monthly_profit_ghs", "has_collateral_or_guarantor", "repayment_months"]

for field in fields_to_check:
    row = {"Field": field, "L001": False, "L003": False, "L006": False}
    correct_matches = 0

    for letter_id in ["L001", "L003", "L006"]:
        # What our AI found
        extracted_val = df.loc[df['Letter_ID'] == letter_id, field].values[0]
        # The correct answer
        gold_val = GOLD[letter_id][field]

        # We do string comparisons just in case there are minor type differences
        if str(extracted_val).lower() == str(gold_val).lower():
            row[letter_id] = True
            correct_matches += 1
        # For strings like 'purpose', exact match is hard, so we check if the words are inside
        elif field == "purpose" and str(extracted_val).lower() in str(gold_val).lower():
            row[letter_id] = True
            correct_matches += 1

    # Calculate percentage
    row["Accuracy %"] = round((correct_matches / 3) * 100, 2)
    results_table.append(row)

# TODO: Display a small table: rows = fields, columns = L001 / L003 / L006 / accuracy.
accuracy_df = pd.DataFrame(results_table)
display(accuracy_df)

"""
**Part 4.2 — Reliability: is the system consistent?**"""

# TODO: Run extract_fields() on letter L004 FIVE times at temperature=0 and FIVE times at temperature=1.0.

def test_reliability(temp_value):
    print(f"Testing Temperature {temp_value}...")
    valid_count = 0
    answers = []

    for i in range(5):
        user_prompt = f"Extract data from this letter:\n\n{LETTERS['L004']}"
        raw_response = ask_llm(user_prompt, system_prompt=EXTRACT_SYSTEM_PROMPT, temperature=temp_value)
        clean_text = raw_response.replace("```json", "").replace("```", "").strip()

        try:
            data = json.loads(clean_text)
            valid_count += 1
            # We save the dictionary as a sorted string so we can easily compare if they are identical
            answers.append(json.dumps(data, sort_keys=True))
        except:
            answers.append(f"FAILED_JSON_{i}")

    # set() removes duplicates, so if length is 1, they were all identical!
    unique_answers = len(set(answers))
    print(f"Valid JSONs: {valid_count}/5 | Unique Answers: {unique_answers} (1 is perfect consistency!)\n")

test_reliability(0.0)
test_reliability(1.0)

"""
**Part 4.3 — Hallucination probing**"""

# System prompt definition so Python doesn't throw a NameError
SYSTEM_PROMPT_V2 = "You are an assistant to a microfinance loan officer. Write a factual, neutral 3-4 sentence summary of the loan application."

print("--- TEST 1: Ask about a detail NOT in the letter ---")
# Does it admit the information is absent, or does it invent one?
fake_question = "What is Akosua Mensah's credit score? Please summarize."
test1_ans = ask_llm(fake_question + "\n\n" + LETTERS['L001'], system_prompt=SYSTEM_PROMPT_V2, temperature=0.0)
print("AI Response:", test1_ans)


print("\n--- TEST 2: Feed the extractor an EMPTY or IRRELEVANT text ---")
# Does it return nulls, or does it fabricate an applicant?
weather_report = "It is going to be 32 degrees Celsius and very sunny in Accra today."
test2_ans = extract_fields(weather_report)
print("AI Response:", test2_ans)

"""**Student Reasoning — Evaluation results**
*1. Report your extraction accuracy. Which field was hardest for the model and why?*
*2. What did the reliability experiment show about temperature and production systems?*
*3. Did your system hallucinate under probing? If yes, how could the prompt (or the system design around it) reduce the risk?*

> **1. Extraction Accuracy:**
> * Name, amount, and collateral were **100% accurate**.
> * The hardest field was **purpose** because it is a full sentence. The AI wrote good descriptions, but they did not match the exact gold text word-for-word.
> * Profit and repayment months showed 0% only because of formatting differences (for example, comparing `900.0` to `900`).
>
> **2. Reliability:**
> * At **temperature 0.0**, all 5 runs gave the exact same answer (1 unique answer).
> * At **temperature 1.0**, the answers changed across runs (2 unique answers).
> * **Takeaway:** Production systems must use temperature 0.0 so data stays 100% consistent and code does not crash.
>
> **3. Hallucination Probing:**
> * **No, the AI did not hallucinate.**
> * In Test 1, it correctly stated that the credit score was missing.
> * In Test 2, it returned none for all fields when reading weather text.
> * Clear rules like "use null" and "do not guess" successfully prevent hallucinations.

**Part 4.4 — Appropriateness: should this system exist?**

**Student Reasoning — Appropriateness**
*1. Letters L002 and L006 would likely be declined. If the bank fully automated decisions with your system, who could be unfairly harmed, and how? Consider applicants who write poorly in English but run solid businesses.*
*2. Loan letters contain personal data. What are the implications of sending them to a third-party API in another country? What would you check before deploying this at a real Ghanaian microfinance institution?*
*3. Name TWO concrete safeguards you would build around this system in production (think: human review points, logging, appeal processes, monitoring).*

> **Answer:**
> 1. If we automate this completely, it could unfairly reject people who are great at business but not very good at writing English letters. The AI might think bad grammar means they are not good, which is not good.
> 2. Sending personal names and money problems to a different country is a huge privacy risk! Before setting this up, I would make sure it doesn't break Ghana's data protection laws.
> 3. Safeguard 1: Every single declined application must be quickly reviewed by a human. Safeguard 2: Create a system log that tracks what the AI says so we can audit if it is unfairly rejecting certain types of people.

**Section 5 — Reflection**

1. **Prompting as engineering:** How is iterating on a prompt similar to and different from iterating on the model hyperparameters you tuned in Lab 3?
2. **Trust:** After your Section 4 evaluation, would you trust this system to run unattended? What single evaluation result most influenced your answer?
3. **Cost and scale:** Estimate (from your `response.usage` numbers) the tokens needed to process 1,000 applications per month. What does that imply for provider choice?
4. **Looking back at the course:** You have now used classical ML (Lab 2), trained neural networks (Lab 3), and used a foundation model via API (Lab 4). For a task like this one, why does calling an API beat training your own model — and when would it not?

> **Answer:**
> 1. It is similar because in both cases you are making small tweaks and testing the results to see if the machine gets smarter. It is different because prompt engineering uses plain English words, while tuning hyperparameters uses math and numbers.
> 2. I would definitely not trust it to run unattended! The hallucination test (and how it struggles with long text strings) shows that the AI can get confused if a letter is written in a weird way.
> 3. If one application uses about 400 tokens, 1,000 applications would use 400,000 tokens. this is cheap on a free tier, but it means if we grow our business, This means I should compare the provider's price, free limit, speed, and privacy before choosing a provider
> 4. I would say that Calling an API is faster and cheaper than spending bit money to build your own AI models. However, if bank or country has extreme privacy laws where customer data can't leave that place , they would have to train their own model so it stays offline and not give their data to other parties.
"""